---
title: "data_tidy_2"
author: "Yurou Liu"
date: "2025-09-24"
output: html_document
---

```{r setup}
library(tidyverse)
```

## joining datasets

import datastes

```{r}
pups_df = 
  read_csv("./data/FAS_pups.csv")

pups_df$`PD ears`[pups_df$`PD ears` %in% c(".")] <- "NA"
pups_df$`PD ears` <- as.numeric(pups_df$`PD ears`)

pups_df = janitor::clean_names(pups_df) %>% 
  mutate(sex = recode(sex, `1` = "male", `2` = "female"))


litters_df = 
  read_csv("./data/FAS_litters.csv") %>% 
  janitor::clean_names() %>%
  relocate(litter_number)

litters_df$gd0_weight[litters_df$gd0_weight %in% c(".")] <- NA
litters_df$gd0_weight <- as.numeric(litters_df$gd0_weight)

litters_df$gd18_weight[litters_df$gd18_weight %in% c(".")] <- NA
litters_df$gd18_weight <- as.numeric(litters_df$gd18_weight)

litters_df = litters_df %>% separate(group, into = c("dose", "day_of_tx"), sep = 3) # separate the "group" column into "dose" and "day_of_tx", from the 3rd character.
```

join them

```{r}
fas_df = 
  left_join(pups_df, litters_df, by = "litter_number") %>% 
  arrange(litter_number) %>%
  relocate(litter_number, dose, day_of_tx)
```